<?php if($block->getData('insert_a_meaningfull_name')):?>
    <div class="custom-image-block">
        <hr >
        <div class="relative"><a href="<?php echo $block->getData('htmlImageBlockLink')?>"> 
            <img class="main-banner-left-image" src="<?php echo $block->getData('insert_a_meaningfull_name')?>"> </a>
            <div class="banner-content-image-2 content-top absolute"><span class="span-image"><?php echo $block->getData('htmlImageBlockTitle')?></span>
            <h4 class="text-name-image-left-2"><strong><?php echo $block->getData('htmlImageBlockText')?></strong></h4>
            </div>
        </div>
    </div>
 
<?php endif?>