
<?php if ($block->getData('htmlBlockHeader')) : ?>
    <div class="collapsible-content">
        <p class="collapsible-title">
            <a class="htmlBlockHeader collapsible"><?php echo $block->getData('htmlBlockHeader'); ?></a>
        </p>

        <div class="content-htmlblock">
            <h4 class="htmlBlockSubtitle subtitle-text"><?php echo $block->getData('htmlBlockSubtitle')?></h4>
            <p class="htmlBlockContent content-text "><?php echo $block->getData('htmlBlockContent')?></p>
        </div>
     
    </div>
<?php endif; ?>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function() {
            this.classList.toggle("collapsible-active");
            let current = document.querySelector('.collapsible-title');
            let content = current.nextElementSibling;
            // var content = this.nextElementSibling;
            if (content.style.maxHeight) {
                content.style.maxHeight = null;
            } else {
                content.style.maxHeight = content.scrollHeight + "px";
            }
        });
    }
</script>